image:
  name: hashicorp/terraform:latest
  entrypoint: [""]

variables:
    TF_IN_AUTOMATION: "1"
    AWS_ACCESS_KEY_ID: ${MY_AWS_KEY}
    AWS_SECRET_ACCESS_KEY: ${MY_SECRET_ACCESS_KEY}
    AWS_REGION: "ap-southeast-1"

stages:
  - validate
  - plan
  - apply
  - destroy
cache:
  paths:
  key: terraform-cache
      - .terraform.tfstate
      - .terraform/ # Cache Terraform dependencies to speed up CI/CD runs
before_script:
  - terraform --version
  - terraform init      
validate: # Validate Terraform configuration files
  stage: validate
  script:
    - terraform validate
  
plan:
  stage: plan
  script:
    - terraform plan -out "tfplan" --var-file = terraform.tfvars
  dependencies:
    - validate
  artifacts:
    paths:
      - tfplan # Store the plan file as an artifact to be used in apply stage

apply: 
  stage: apply
  variables:
  script:
    - terraform apply -input=false "tfplan" # Apply the saved Terraform plan
  dependencies:
    - plan
  when: manual # Require manual approval before applying 
  artifacts:
    paths:
      - terraform.tfstate

destroy:
  stage: destroy
  script:
    - terraform destroy --var-file "terraform.tfvars" -auto-approve
  when: manual # Require manual approval before destroying infrastructure
  dependencies: 
    - apply # Destroy all Terraform-managed infrastructure
 




























